// Command docgen writes a complete markdown reference of every flareadm leaf
// command to stdout.
//
// It builds the real cobra command tree, so the reference can never drift from
// the shipped command surface. It never loads configuration, reads credentials
// or touches the network: the same guarantee as `flareadm <command> --help`.
//
// Usage:
//
//	go run ./tools/docgen > docs/commands.md
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/hnkNkm/flareadm/cmd"
	"github.com/hnkNkm/flareadm/internal/app"
)

func main() {
	if err := run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

func run(out io.Writer) error {
	reference := generate(newRoot())
	w := bufio.NewWriter(out)
	if _, err := w.WriteString(reference); err != nil {
		return err
	}
	return w.Flush()
}

// newRoot builds the command tree exactly as the CLI does, without executing
// anything.
func newRoot() *cobra.Command {
	rt := app.NewRuntime(strings.NewReader(""), io.Discard, io.Discard)
	return cmd.NewCommand(rt)
}

// generate renders the reference. The output is deterministic: commands are
// walked in the same order the help output lists them (cobra sorts children by
// name) and flags are visited in name order, so two runs are byte-identical.
func generate(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("# FlareADM command reference\n\n")
	b.WriteString("Generated by `go run ./tools/docgen > docs/commands.md`. Do not edit by hand.\n\n")
	leaves := leafCommands(root)
	fmt.Fprintf(&b, "This reference covers %d commands.\n\n", len(leaves))
	for _, leaf := range leaves {
		writeCommand(&b, leaf)
	}
	return b.String()
}

// leafCommands walks the tree depth-first and returns every command without
// subcommands, skipping cobra's auto-generated help command.
func leafCommands(c *cobra.Command) []*cobra.Command {
	children := c.Commands()
	leaves := make([]*cobra.Command, 0, len(children))
	for _, child := range children {
		if child.Name() == "help" {
			continue
		}
		if len(child.Commands()) == 0 {
			leaves = append(leaves, child)
			continue
		}
		leaves = append(leaves, leafCommands(child)...)
	}
	return leaves
}

func writeCommand(b *strings.Builder, c *cobra.Command) {
	c.InitDefaultHelpFlag()
	fmt.Fprintf(b, "## `%s`\n\n", c.CommandPath())
	short := strings.TrimSpace(c.Short)
	long := strings.TrimSpace(c.Long)
	if short != "" {
		fmt.Fprintf(b, "%s\n\n", short)
	}
	if long != "" && long != short {
		fmt.Fprintf(b, "%s\n\n", long)
	}
	fmt.Fprintf(b, "```text\n%s\n```\n\n", c.UseLine())
	writeFlags(b, "Flags", c.NonInheritedFlags())
	writeFlags(b, "Global flags", c.InheritedFlags())
}

// writeFlags renders a flag set in name order (pflag's visit order).
func writeFlags(b *strings.Builder, title string, set *pflag.FlagSet) {
	lines := make([]string, 0, set.NFlag())
	set.VisitAll(func(f *pflag.Flag) {
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		if f.Value.Type() != "bool" {
			name += " " + f.Value.Type()
		}
		line := fmt.Sprintf("- `%s` — %s", name, strings.TrimSpace(f.Usage))
		if f.DefValue != "" && !isZeroDefault(f.DefValue) {
			line += fmt.Sprintf(" (default `%s`)", f.DefValue)
		}
		lines = append(lines, line)
	})
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "**%s:**\n\n", title)
	for _, line := range lines {
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

// isZeroDefault reports whether a pflag default value carries no information.
func isZeroDefault(def string) bool {
	switch def {
	case "false", "0", "0s", "[]", "map[]", "0.0":
		return true
	}
	return false
}
