version: 2

project_name: flareadm

before:
  hooks:
    - go mod tidy

builds:
  - id: flareadm
    main: .
    binary: flareadm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hnkNkm/flareadm/internal/version.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: flareadm
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

sboms:
  - artifacts: archive

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
