// Command scopegen turns the live Cloudflare OAuth scope list into the Go
// catalog used by `flareadm auth login`.
//
// The input is the raw response of `GET /oauth/scopes` (the API envelope with a
// `result` array, or the bare array). The output is a Go file holding the ids
// grouped by the category the API reports, sorted so regeneration is
// byte-for-byte reproducible.
//
// Usage:
//
//	flareadm api request GET /oauth/scopes | go run ./tools/scopegen -out cmd/auth/scopes_generated.go
//
// or, from the committed capture:
//
//	go run ./tools/scopegen -in tools/scopegen/testdata/oauth_scopes.json -out cmd/auth/scopes_generated.go
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

// defaultTestdata is the captured live response committed for reproducible
// regeneration and for the freshness test.
const defaultTestdata = "tools/scopegen/testdata/oauth_scopes.json"

// header is the first line of the generated file. It doubles as the
// regeneration instruction.
const header = `// Code generated by "go run ./tools/scopegen -in tools/scopegen/testdata/oauth_scopes.json -out cmd/auth/scopes_generated.go"; DO NOT EDIT.

package auth

`

func main() {
	in := flag.String("in", "", "input file with the GET /oauth/scopes response (default: stdin)")
	out := flag.String("out", "", "output file (default: stdout)")
	flag.Parse()

	var (
		raw []byte
		err error
	)
	if *in == "" {
		raw, err = io.ReadAll(os.Stdin)
	} else {
		raw, err = os.ReadFile(*in)
	}
	if err != nil {
		fail(err)
	}
	generated, err := generate(raw)
	if err != nil {
		fail(err)
	}
	if *out == "" {
		if _, err := os.Stdout.Write(generated); err != nil {
			fail(err)
		}
		return
	}
	if err := os.WriteFile(*out, generated, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "scopegen:", err)
	os.Exit(1)
}

// scopeEntry is one entry of the GET /oauth/scopes result array.
type scopeEntry struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Category string `json:"category"`
}

// generate renders the catalog for the raw scope response. Categories and the
// ids inside them are sorted, so the same input always produces the same bytes.
func generate(raw []byte) ([]byte, error) {
	entries, err := parse(raw)
	if err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("no scopes found in the input")
	}

	byCategory := map[string][]string{}
	names := map[string]string{}
	seen := map[string]string{}
	for _, entry := range entries {
		if entry.ID == "" {
			return nil, fmt.Errorf("scope entry without an id: %q", entry.Name)
		}
		if previous, ok := seen[entry.ID]; ok {
			return nil, fmt.Errorf("duplicate scope id %q (categories %s and %s)", entry.ID, previous, entry.Category)
		}
		category := entry.Category
		if category == "" {
			category = "other"
		}
		seen[entry.ID] = category
		names[entry.ID] = entry.Name
		byCategory[category] = append(byCategory[category], entry.ID)
	}

	categories := make([]string, 0, len(byCategory))
	for category := range byCategory {
		categories = append(categories, category)
	}
	sort.Strings(categories)
	for _, category := range categories {
		sort.Strings(byCategory[category])
	}

	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "// liveScopeGroups is the OAuth scope catalog Cloudflare reports for\n")
	fmt.Fprintf(&b, "// GET /oauth/scopes, grouped by the API's own category field. It is the\n")
	fmt.Fprintf(&b, "// authoritative list: `--scopes` accepts exactly these ids (plus the\n")
	fmt.Fprintf(&b, "// protocol scopes in oauth.RequiredScopes), and the ids this CLI requests by\n")
	fmt.Fprintf(&b, "// default are checked against it (see scopeGroups in scopes.go).\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// %d scopes in %d categories.\n", len(entries), len(categories))
	fmt.Fprintf(&b, "var liveScopeGroups = []liveScopeGroup{\n")
	for _, category := range categories {
		fmt.Fprintf(&b, "\t{\n\t\tCategory: %q,\n\t\tIDs: []string{\n", category)
		for _, id := range byCategory[category] {
			fmt.Fprintf(&b, "\t\t\t%q,\n", id)
		}
		fmt.Fprintf(&b, "\t\t},\n\t},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "// liveScopeNames is the human-readable name Cloudflare gives each id, as\n")
	fmt.Fprintf(&b, "// reported by GET /oauth/scopes.\n")
	fmt.Fprintf(&b, "var liveScopeNames = map[string]string{\n")
	ids := make([]string, 0, len(names))
	for id := range names {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		fmt.Fprintf(&b, "\t%q: %q,\n", id, names[id])
	}
	b.WriteString("}\n")

	// The output must be gofmt-clean: an unformatted generated file would fail
	// `gofmt -l .` on every checkout.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting the generated file: %w", err)
	}
	return formatted, nil
}

// parse accepts either the API envelope ({"result": [...]}) or a bare array.
func parse(raw []byte) ([]scopeEntry, error) {
	var envelope struct {
		Result []scopeEntry `json:"result"`
	}
	if err := json.Unmarshal(raw, &envelope); err == nil && len(envelope.Result) > 0 {
		return envelope.Result, nil
	}
	var bare []scopeEntry
	if err := json.Unmarshal(raw, &bare); err != nil {
		return nil, fmt.Errorf("decoding the /oauth/scopes response: %w", err)
	}
	return bare, nil
}
